// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZyBiSlKHU32_FQnzrInarI9fO9QYkds',
    appId: '1:645779248201:web:d8981cb8362ba9d6cedb98',
    messagingSenderId: '645779248201',
    projectId: 'gardencompanion2',
    authDomain: 'gardencompanion2.firebaseapp.com',
    storageBucket: 'gardencompanion2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCwLTREc6ywDz7bPf1wD2Vt8bkXResvYg',
    appId: '1:645779248201:android:062dc5e0f713d2c0cedb98',
    messagingSenderId: '645779248201',
    projectId: 'gardencompanion2',
    storageBucket: 'gardencompanion2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtD80Tyz3kNvQiYny7G1IaK3ydXBymp8o',
    appId: '1:645779248201:ios:983d654b5a477f9ccedb98',
    messagingSenderId: '645779248201',
    projectId: 'gardencompanion2',
    storageBucket: 'gardencompanion2.appspot.com',
    iosClientId: '645779248201-tqh7apnkvv2htg283e2uamfpp88fkueu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenCompanion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtD80Tyz3kNvQiYny7G1IaK3ydXBymp8o',
    appId: '1:645779248201:ios:c9be271e472310bccedb98',
    messagingSenderId: '645779248201',
    projectId: 'gardencompanion2',
    storageBucket: 'gardencompanion2.appspot.com',
    iosClientId: '645779248201-9ev4co28ktueoghji7v15cugoo96evl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenCompanion2.RunnerTests',
  );
}
