// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5G6ua3vQgAJaWpo3Qqu9ZUtCSRA5FJ8k',
    appId: '1:402219795191:web:edc6838c1ee0f080dfc9f2',
    messagingSenderId: '402219795191',
    projectId: 'garden-companion-1d9eb',
    authDomain: 'garden-companion-1d9eb.firebaseapp.com',
    storageBucket: 'garden-companion-1d9eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeajkuzudjbLZetdHxoLOYXuPPfpUA_I',
    appId: '1:402219795191:android:4255011c905be152dfc9f2',
    messagingSenderId: '402219795191',
    projectId: 'garden-companion-1d9eb',
    storageBucket: 'garden-companion-1d9eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFCJxpzPknc_7TQinUoq9ioBEACn_X94M',
    appId: '1:402219795191:ios:43d9da7c77f81fc0dfc9f2',
    messagingSenderId: '402219795191',
    projectId: 'garden-companion-1d9eb',
    storageBucket: 'garden-companion-1d9eb.appspot.com',
    iosClientId: '402219795191-rbj0o1ghd34s9846nje087vdip6in2b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFCJxpzPknc_7TQinUoq9ioBEACn_X94M',
    appId: '1:402219795191:ios:103b8a922f0817e8dfc9f2',
    messagingSenderId: '402219795191',
    projectId: 'garden-companion-1d9eb',
    storageBucket: 'garden-companion-1d9eb.appspot.com',
    iosClientId: '402219795191-g5iblli1s2ab0ortqhoep879426l128a.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenCompanion.RunnerTests',
  );
}
